{{- if .Values.applications }}
{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
spec:
  destination:
    namespace: {{ $.Release.Namespace }}
    server: https://kubernetes.default.svc
  project: "default"
  source:
    {{- toYaml .source | nindent 4 }}
{{- end }}
{{- end }}
