---
apiVersion: v2
name: argocd-init
description: Install Argocd and Initial RBAC & Applications
keywords:
  - argocd
version: 1.0.2
appVersion: v2.4.4
maintainers:
  - name: prastamaha
    email: prastamaha@gmail.com
    url: https://prastamaha.com
dependencies:
  - name: argo-cd
    alias: argocd
    version: "4.9.12"
    repository: "https://argoproj.github.io/argo-helm"
