# argocd configurations
argocd:
  server:
    # rbac config should be disable, because it will be handle by argocd-init chart
    rbacConfigCreate: false
    admin.enabled: true
    config:
      url: "https://argocd.example.com"
      dex.config: |
        connectors:
        - config:
            issuer: https://accounts.google.com
            clientID: <CLIENT_ID>
            clientSecret: <CLIENT_SECRET>
          type: oidc
          id: google
          name: Google
    extraArgs:
    - --insecure
    ingress:
      enabled: false
      ingressClassName: kong
      annotations:
        konghq.com/https-redirect-status-code: "301"
        konghq.com/protocols: https
      hosts:
        - argocd.example.com
      tls:
      - secretName: argocd-secret
        hosts:
        - argocd.example.com

rbac:
  # options: ["", "role:readonly"]
  defaultPolicy: ""

  # customProjectRoles will create project scope rbac
  # for example:
  # ...
  # customProjectRoles:
  #   - logging
  # ...
  # that would create ["logging-admin", "logging-viewer", "logging-developer", "logging-contributor"].
  # *-admin: can do anything to its project
  # *-viewer: only can view the resources under project
  # *-developer: *-viewer + can sync and override applications under project
  # *-contributor: can to anything except delete the project
  customProjectRoles:
    - default

  # email should using google login
  # roles options: ["admin", "readonly"] and customProjectRoles
  users: []
    # - email: admin@example.com
    #   roles:
    #     - admin 
    # - email: user@example.com
    #   roles:
    #     - default-contributor

# take a look this docs as references: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#quick-reference
# argocd will create repository as a secret
# type parameter will used to determine are we using stringData or data in the secret
repositories:
  - name: example-repository
    data:
      name: <name with base64 encode>
      type: <type with base64 encode>
      url: <url with base64 encode>
      project: <project with base64 encode>
      sshPrivateKey: <sshPrivateKey with base64 encode>
    
# init argocd applications
applications:
  - name: example-app
    source:
      repoURL: ""
      path: ""
      targetRevision: "HEAD"
      helm:
        valueFiles: []
